// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PDSCalculatorDesktop.Data;

#nullable disable

namespace PDSCalculatorDesktop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251126004832_RefactorDatabaseSchema")]
    partial class RefactorDatabaseSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PDSCalculatorDesktop.Models.BackgroundConcentration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Concentration")
                        .HasColumnType("double precision");

                    b.Property<int>("ControlPointId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SubstanceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementDate");

                    b.HasIndex("SubstanceId");

                    b.HasIndex("ControlPointId", "SubstanceId", "MeasurementDate")
                        .IsUnique();

                    b.ToTable("BackgroundConcentrations", t =>
                        {
                            t.HasCheckConstraint("CK_BackgroundConcentrations_Concentration", "\"Concentration\" >= 0");
                        });
                });

            modelBuilder.Entity("PDSCalculatorDesktop.Models.ControlPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("WaterUseTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("WaterUseTypeId");

                    b.ToTable("ControlPoints");
                });

            modelBuilder.Entity("PDSCalculatorDesktop.Models.Discharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("ControlPointId")
                        .HasColumnType("integer");

                    b.Property<int>("EnterpriseId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ControlPointId");

                    b.HasIndex("EnterpriseId");

                    b.ToTable("Discharges");
                });

            modelBuilder.Entity("PDSCalculatorDesktop.Models.DischargeConcentration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Concentration")
                        .HasColumnType("double precision");

                    b.Property<int>("DischargeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SubstanceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementDate");

                    b.HasIndex("SubstanceId");

                    b.HasIndex("DischargeId", "SubstanceId", "MeasurementDate")
                        .IsUnique();

                    b.ToTable("DischargeConcentrations", t =>
                        {
                            t.HasCheckConstraint("CK_DischargeConcentrations_Concentration", "\"Concentration\" >= 0");
                        });
                });

            modelBuilder.Entity("PDSCalculatorDesktop.Models.Enterprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Enterprises");
                });

            modelBuilder.Entity("PDSCalculatorDesktop.Models.Substance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("KNK")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Substances", t =>
                        {
                            t.HasCheckConstraint("CK_Substances_KNK", "\"KNK\" >= 0");
                        });
                });

            modelBuilder.Entity("PDSCalculatorDesktop.Models.SubstanceWaterUseCharacteristic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupLFV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("HazardClass")
                        .HasColumnType("integer");

                    b.Property<double>("PDK")
                        .HasColumnType("double precision");

                    b.Property<int>("SubstanceId")
                        .HasColumnType("integer");

                    b.Property<int>("WaterUseTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WaterUseTypeId");

                    b.HasIndex("SubstanceId", "WaterUseTypeId")
                        .IsUnique();

                    b.ToTable("SubstanceWaterUseCharacteristics", t =>
                        {
                            t.HasCheckConstraint("CK_SubstanceWaterUseCharacteristics_HazardClass", "\"HazardClass\" BETWEEN 1 AND 4");

                            t.HasCheckConstraint("CK_SubstanceWaterUseCharacteristics_PDK", "\"PDK\" > 0");
                        });
                });

            modelBuilder.Entity("PDSCalculatorDesktop.Models.TechnicalParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Diameter")
                        .HasColumnType("double precision");

                    b.Property<double>("DischargeAngle")
                        .HasColumnType("double precision");

                    b.Property<int>("DischargeId")
                        .HasColumnType("integer");

                    b.Property<double>("DistanceToControlPoint")
                        .HasColumnType("double precision");

                    b.Property<double>("DistanceToShore")
                        .HasColumnType("double precision");

                    b.Property<double>("DistanceToWaterSurface")
                        .HasColumnType("double precision");

                    b.Property<double>("FlowRate")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("WaterFlowVelocity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DischargeId");

                    b.HasIndex("ValidFrom");

                    b.ToTable("TechnicalParameters", t =>
                        {
                            t.HasCheckConstraint("CK_TechnicalParameters_Diameter", "\"Diameter\" > 0");

                            t.HasCheckConstraint("CK_TechnicalParameters_DischargeAngle", "\"DischargeAngle\" >= 0 AND \"DischargeAngle\" <= 360");

                            t.HasCheckConstraint("CK_TechnicalParameters_DistanceToControlPoint", "\"DistanceToControlPoint\" > 0");

                            t.HasCheckConstraint("CK_TechnicalParameters_DistanceToShore", "\"DistanceToShore\" > 0");

                            t.HasCheckConstraint("CK_TechnicalParameters_DistanceToWaterSurface", "\"DistanceToWaterSurface\" > 0");

                            t.HasCheckConstraint("CK_TechnicalParameters_FlowRate", "\"FlowRate\" > 0");

                            t.HasCheckConstraint("CK_TechnicalParameters_WaterFlowVelocity", "\"WaterFlowVelocity\" > 0");
                        });
                });

            modelBuilder.Entity("PDSCalculatorDesktop.Models.WaterUseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("WaterUseTypes");
                });

            modelBuilder.Entity("PDSCalculatorDesktop.Models.BackgroundConcentration", b =>
                {
                    b.HasOne("PDSCalculatorDesktop.Models.ControlPoint", "ControlPoint")
                        .WithMany("BackgroundConcentrations")
                        .HasForeignKey("ControlPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PDSCalculatorDesktop.Models.Substance", "Substance")
                        .WithMany("BackgroundConcentrations")
                        .HasForeignKey("SubstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ControlPoint");

                    b.Navigation("Substance");
                });

            modelBuilder.Entity("PDSCalculatorDesktop.Models.ControlPoint", b =>
                {
                    b.HasOne("PDSCalculatorDesktop.Models.WaterUseType", "WaterUseType")
                        .WithMany("ControlPoints")
                        .HasForeignKey("WaterUseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WaterUseType");
                });

            modelBuilder.Entity("PDSCalculatorDesktop.Models.Discharge", b =>
                {
                    b.HasOne("PDSCalculatorDesktop.Models.ControlPoint", "ControlPoint")
                        .WithMany("Discharges")
                        .HasForeignKey("ControlPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PDSCalculatorDesktop.Models.Enterprise", "Enterprise")
                        .WithMany("Discharges")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ControlPoint");

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("PDSCalculatorDesktop.Models.DischargeConcentration", b =>
                {
                    b.HasOne("PDSCalculatorDesktop.Models.Discharge", "Discharge")
                        .WithMany("DischargeConcentrations")
                        .HasForeignKey("DischargeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PDSCalculatorDesktop.Models.Substance", "Substance")
                        .WithMany("DischargeConcentrations")
                        .HasForeignKey("SubstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Discharge");

                    b.Navigation("Substance");
                });

            modelBuilder.Entity("PDSCalculatorDesktop.Models.SubstanceWaterUseCharacteristic", b =>
                {
                    b.HasOne("PDSCalculatorDesktop.Models.Substance", "Substance")
                        .WithMany("WaterUseCharacteristics")
                        .HasForeignKey("SubstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PDSCalculatorDesktop.Models.WaterUseType", "WaterUseType")
                        .WithMany("SubstanceCharacteristics")
                        .HasForeignKey("WaterUseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Substance");

                    b.Navigation("WaterUseType");
                });

            modelBuilder.Entity("PDSCalculatorDesktop.Models.TechnicalParameters", b =>
                {
                    b.HasOne("PDSCalculatorDesktop.Models.Discharge", "Discharge")
                        .WithMany("TechnicalParameters")
                        .HasForeignKey("DischargeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discharge");
                });

            modelBuilder.Entity("PDSCalculatorDesktop.Models.ControlPoint", b =>
                {
                    b.Navigation("BackgroundConcentrations");

                    b.Navigation("Discharges");
                });

            modelBuilder.Entity("PDSCalculatorDesktop.Models.Discharge", b =>
                {
                    b.Navigation("DischargeConcentrations");

                    b.Navigation("TechnicalParameters");
                });

            modelBuilder.Entity("PDSCalculatorDesktop.Models.Enterprise", b =>
                {
                    b.Navigation("Discharges");
                });

            modelBuilder.Entity("PDSCalculatorDesktop.Models.Substance", b =>
                {
                    b.Navigation("BackgroundConcentrations");

                    b.Navigation("DischargeConcentrations");

                    b.Navigation("WaterUseCharacteristics");
                });

            modelBuilder.Entity("PDSCalculatorDesktop.Models.WaterUseType", b =>
                {
                    b.Navigation("ControlPoints");

                    b.Navigation("SubstanceCharacteristics");
                });
#pragma warning restore 612, 618
        }
    }
}
